name: "maven CI workflow OS matrix"

on:
  push:
    # branches: [ $default-branch ]
    branches: [ dev ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  
 

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-a-specific-python-version
  build-maven-os-matrix:
    name: "OS matrix"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # https://github.com/actions/setup-java
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 1.6, 6.0.83, 7, 7.0.181, 8, 8.0.192, 9.0.x, 10, 11.0.x, 11.0.3, 12, 13 ]
        # java: [ 11.0.3, 12, 13 ]
        # python-version: [2.7, 3.6, 3.7, 3.8, pypy2, pypy3]
        # exclude:
        #   - os: macos-latest
        #     python-version: 3.6
        #   - os: windows-latest
        #     python-version: 3.6
    steps:
      - uses: actions/checkout@v2
      - name: "Setup java"
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # - name: "Setup java"
      #   run: java -cp java HelloWorldApp        
